FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /

# Instalar las dependencias de tu aplicación
RUN pip3 install pandas
RUN pip3 install joblib
RUN pip3 install scikit-learn==1.3.2

# Crear un directorio para las credenciales y copiarlas al contenedor
RUN mkdir -p /root/.config/gcloud/
COPY gcp-credentials.json /root/.config/gcloud/application_default_credentials.json

# Copiar el código de tu aplicación al contenedor
COPY trainer /trainer


# Establecer el punto de entrada para tu aplicación
ENTRYPOINT ["python", "-m", "trainer.task"]